# fly.toml app configuration file generated for analyticstime-8zqkwg on 2025-09-16T20:29:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'analyticstime-8zqkwg'
primary_region = 'den'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
